import os
import json
import uuid
from typing import List, Dict, Any
import numpy as np
import pandas as pd
from app.services.data_service import DataService
from app.config import settings

class JupyterService:
    """
    Compiles an Action Ledger into a Kaggle-style Jupyter Notebook (.ipynb).
    """

    @staticmethod
    def generate_notebook(dataset_id: str) -> str:
        """
        Generates a Jupyter Notebook based on the user's recorded actions
        and comprehensive EDA/ML templates. Returns the path to the .ipynb file.
        """
        dataset_info = DataService.get_dataset_info(dataset_id)
        ledger = DataService.get_action_ledger(dataset_id)
        dataset_name = dataset_info.get("filename", "dataset.csv")

        cells = []
        
        # Helper to add markdown cells
        def add_md(text: str):
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [text]
            })

        # Helper to add code cells
        def add_code(code: str):
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [code]
            })

        # 1. Header
        add_md(f"# 📊 Infinitics AI: Automated Analysis Notebook\n\nThis notebook was automatically generated by Infinitics AI based on the interactive data cleaning and analysis you performed on `{dataset_name}`. It contains all the necessary preprocessing, exploratory data analysis (EDA), and basic model setup steps.")

        # 2. Imports
        add_md("## 1. Environment Setup & Imports\nImporting the necessary standard libraries for data manipulation, visualization, and machine learning.")
        add_code("import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport warnings\n\nwarnings.filterwarnings('ignore')\n%matplotlib inline\n\n# Configure visual styling\nsns.set_theme(style='darkgrid', palette='muted')")

        # 3. Data Loading
        add_md(f"## 2. Data Loading\nLoading `{dataset_name}` into a Pandas DataFrame.")
        add_code(f"file_path = '{dataset_name}' # Update this path to where your dataset is stored locally.\ndf = pd.read_csv(file_path)\n\n# Display basic information\ndf.info()\ndisplay(df.head())")

        # Separate actions into buckets
        cleaning_actions = [a for a in ledger if not a['action'].startswith('viz_') and not a['action'].startswith('ml_') and not a['action'].startswith('fe_') and not a['action'].startswith('sql_')]
        fe_actions = [a for a in ledger if a['action'].startswith('fe_')]
        viz_actions = [a for a in ledger if a['action'].startswith('viz_')]
        ml_actions = [a for a in ledger if a['action'].startswith('ml_')]

        # 4. Data Preprocessing & Cleaning (pandas only)
        add_md("## 3. Data Preprocessing & Cleaning\nReplaying the exact cleaning operations performed in the Infinitics UI.")
        
        cleaning_code_lines = []
        if not cleaning_actions:
            cleaning_code_lines.append("# No specific cleaning operations were performed in the UI.")
        
        for idx, step in enumerate(cleaning_actions):
            action = step["action"]
            p = step["params"]
            cleaning_code_lines.append(f"\n# Step {idx+1}: {action}")
            
            if action == "missing_values":
                strat = p.get("strategy")
                cols = p.get("columns")
                cols_str = f"df.columns" if not cols else str(cols)
                if strat == "drop_rows":
                    cleaning_code_lines.append(f"df = df.dropna(subset={cols_str})")
                elif strat == "drop_cols":
                    cleaning_code_lines.append(f"df = df.drop(columns={cols_str})")
                elif strat == "fill_mean":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    if pd.api.types.is_numeric_dtype(df[col]):\n        df[col] = df[col].fillna(df[col].mean())")
                elif strat == "fill_median":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    if pd.api.types.is_numeric_dtype(df[col]):\n        df[col] = df[col].fillna(df[col].median())")
                elif strat == "fill_mode":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    mode_val = df[col].mode()\n    if not mode_val.empty:\n        df[col] = df[col].fillna(mode_val.iloc[0])")
                elif strat == "fill_constant":
                    cleaning_code_lines.append(f"df[{cols_str}] = df[{cols_str}].fillna({repr(p.get('fill_value'))})")
                else:
                    cleaning_code_lines.append(f"# Applied missing value strategy: {strat} on {cols_str}")

            elif action == "remove_duplicates":
                subset = p.get("subset")
                cleaning_code_lines.append(f"df = df.drop_duplicates(subset={subset})")

            elif action == "drop_columns":
                cleaning_code_lines.append(f"df = df.drop(columns={p.get('columns')})")

            elif action == "rename_columns":
                cleaning_code_lines.append(f"df = df.rename(columns={p.get('rename_map')})")

            elif action == "convert_dtype":
                cleaning_code_lines.append(f"df['{p.get('column')}'] = df['{p.get('column')}'].astype('{p.get('target_dtype')}')")

            elif action == "handle_outliers":
                cleaning_code_lines.append(f"# Handled outliers for {p.get('column')} using {p.get('method')} ({p.get('strategy')})")
                if p.get('strategy') == 'remove':
                    cleaning_code_lines.append(f"# Removing {p.get('column')} outliers...")

            elif action == "normalize":
                cleaning_code_lines.append(f"# Normalized {p.get('columns')} using {p.get('method')} scaler")

            elif action == "encode_column":
                cleaning_code_lines.append(f"# Encoded categorical column {p.get('column')} using {p.get('method')} encoding")

            else:
                cleaning_code_lines.append(f"# Operation {action} applied with params {p}")

        add_code("\n".join(cleaning_code_lines))

        # 5. EDA & Feature Engineering
        add_md("## 4. Exploratory Data Analysis (EDA) & Feature Engineering\nVisualizing features and applying feature engineering steps (polynomial combinations, date extractions, ratio metrics, PCA, or feature selection).")
        
        eda_code = (
            "# Missing Values Heatmap\n"
            "plt.figure(figsize=(10, 6))\n"
            "sns.heatmap(df.isnull(), yticklabels=False, cbar=False, cmap='viridis')\n"
            "plt.title('Missing Values Distribution')\n"
            "plt.show()\n\n"
            "# Distribution of Numerical Features\n"
            "numerical_cols = df.select_dtypes(include=np.number).columns\n"
            "if len(numerical_cols) > 0:\n"
            "    df[numerical_cols].hist(figsize=(15, 10), bins=20, edgecolor='black')\n"
            "    plt.suptitle('Histograms of Numerical Features')\n"
            "    plt.tight_layout()\n"
            "    plt.show()\n\n"
            "# Correlation Matrix Heatmap\n"
            "if len(numerical_cols) > 1:\n"
            "    plt.figure(figsize=(12, 8))\n"
            "    sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)\n"
            "    plt.title('Correlation Matrix')\n"
            "    plt.show()"
        )
        add_code(eda_code)

        fe_code_lines = []
        fe_code_lines.append("# --- Feature Engineering Templates & Operations ---")
        
        # Add actual ledger actions if they exist
        for idx, step in enumerate(fe_actions):
            action = step["action"]
            p = step["params"]
            fe_code_lines.append(f"\n# Step {idx+1}: {action} (from UI)")
            
            if action == "fe_polynomial":
                fe_code_lines.extend([
                    f"from sklearn.preprocessing import PolynomialFeatures",
                    f"cols = {p.get('columns')}",
                    f"poly = PolynomialFeatures(degree={p.get('degree', 2)}, interaction_only={p.get('interaction_only', False)}, include_bias=False)",
                    f"X_poly = poly.fit_transform(df[cols].dropna())",
                    f"poly_df = pd.DataFrame(X_poly, columns=poly.get_feature_names_out(cols))",
                    f"new_cols = [n for n in poly_df.columns if n not in df.columns]",
                    f"df = pd.concat([df, poly_df[new_cols]], axis=1)"
                ])
            elif action == "fe_date":
                col = p.get('column')
                fe_code_lines.extend([
                    f"df['{col}'] = pd.to_datetime(df['{col}'], errors='coerce')",
                    f"df['{col}_year'] = df['{col}'].dt.year",
                    f"df['{col}_month'] = df['{col}'].dt.month",
                    f"df['{col}_day'] = df['{col}'].dt.day",
                    f"df['{col}_dayofweek'] = df['{col}'].dt.dayofweek",
                    f"for nc in ['{col}_year', '{col}_month', '{col}_day', '{col}_dayofweek']:",
                    f"    df[nc] = df[nc].fillna(df[nc].median() if not df[nc].empty else 0)"
                ])
            elif action == "fe_ratio":
                c1 = p.get('column1')
                c2 = p.get('column2')
                new_col = p.get('new_feature')
                fe_code_lines.extend([
                    f"df['{new_col}'] = df['{c1}'] / df['{c2}'].replace(0, np.nan)",
                    f"df['{new_col}'] = df['{new_col}'].fillna(0)"
                ])

        # Always include template boilerplate for the user to execute manually
        fe_code_lines.extend([
            "\n# Template: Extract Year/Month/Day from a Date Column",
            "# date_col = 'date' # Replace with your date column name",
            "# if date_col in df.columns:",
            "#     df[date_col] = pd.to_datetime(df[date_col], errors='coerce')",
            "#     df[f'{date_col}_year'] = df[date_col].dt.year",
            "#     df[f'{date_col}_month'] = df[date_col].dt.month",
            "#     df[f'{date_col}_day'] = df[date_col].dt.day",
            "#     df[f'{date_col}_dayofweek'] = df[date_col].dt.dayofweek",
            "",
            "# Template: Create Derived Ratio Feature",
            "# num1, num2 = 'amount', 'quantity' # Replace with numerator and denominator column names",
            "# if num1 in df.columns and num2 in df.columns:",
            "#     df[f'{num1}_per_{num2}'] = df[num1] / df[num2].replace(0, np.nan)",
            "#     df[f'{num1}_per_{num2}'] = df[f'{num1}_per_{num2}'].fillna(0)",
            "",
            "# Template: Principal Component Analysis (PCA)",
            "# from sklearn.decomposition import PCA",
            "# from sklearn.preprocessing import StandardScaler",
            "# num_cols = df.select_dtypes(include=np.number).columns.tolist()",
            "# if len(num_cols) >= 2:",
            "#     X_scaled = StandardScaler().fit_transform(df[num_cols].dropna())",
            "#     pca = PCA(n_components=2)",
            "#     pca_res = pca.fit_transform(X_scaled)",
            "#     df['PC1'] = pca_res[:, 0]",
            "#     df['PC2'] = pca_res[:, 1]",
            "#     print('Cumulative variance explained:', np.sum(pca.explained_variance_ratio_))"
        ])
        add_code("\n".join(fe_code_lines))

        # 6. Custom Visualizations
        if viz_actions:
            add_md("## 5. Custom Visualizations\nReproducing the exact custom charts generated in the Infinitics UI.")
            
            seen_viz = set()
            viz_code_lines = []
            
            for step in reversed(viz_actions):
                action = step["action"]
                p = step["params"]
                
                cols_sig = "-".join([str(v) for k, v in p.items() if 'col' in k or 'column' in k])
                sig = f"{action}_{cols_sig}"
                
                if sig in seen_viz:
                    continue
                seen_viz.add(sig)
                
                viz_code_lines.append(f"\n# {action} on {cols_sig}")
                viz_code_lines.append("plt.figure(figsize=(10, 6))")
                
                if action == "viz_histogram":
                    viz_code_lines.append(f"sns.histplot(data=df, x='{p.get('column')}', bins={p.get('bins', 30)}, kde=True)")
                elif action == "viz_bar":
                    if p.get('y_col'):
                        viz_code_lines.append(f"sns.barplot(data=df, x='{p.get('x_col')}', y='{p.get('y_col')}')")
                    else:
                        viz_code_lines.append(f"df['{p.get('x_col')}'].value_counts().head({p.get('top_n', 20)}).plot(kind='bar')")
                elif action == "viz_scatter":
                    hue_str = f", hue='{p.get('color_col')}'" if p.get('color_col') else ""
                    viz_code_lines.append(f"sns.scatterplot(data=df, x='{p.get('x_col')}', y='{p.get('y_col')}'{hue_str})")
                elif action == "viz_line":
                    viz_code_lines.append(f"sns.lineplot(data=df, x='{p.get('x_col')}', y='{p.get('y_col')}')")
                elif action == "viz_box":
                    if p.get('group_col'):
                        viz_code_lines.append(f"sns.boxplot(data=df, x='{p.get('group_col')}', y='{p.get('column')}')")
                    else:
                        viz_code_lines.append(f"sns.boxplot(data=df, y='{p.get('column')}')")
                elif action == "viz_pie":
                    viz_code_lines.append(f"df['{p.get('column')}'].value_counts().head({p.get('top_n', 10)}).plot.pie(autopct='%1.1f%%')\nplt.ylabel('')")
                elif action == "viz_heatmap":
                    viz_code_lines.append(f"sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')")
                elif action == "viz_violin":
                    if p.get('group_col'):
                        viz_code_lines.append(f"sns.violinplot(data=df, x='{p.get('group_col')}', y='{p.get('column')}')")
                    else:
                        viz_code_lines.append(f"sns.violinplot(data=df, y='{p.get('column')}')")
                else:
                    viz_code_lines.append(f"# (Code for {action} omitted in export)")
                    
                viz_code_lines.append("plt.title(f'Custom Chart: {action}')")
                viz_code_lines.append("plt.tight_layout()\nplt.show()")
                
            viz_code_lines.reverse()
            add_code("\n".join(viz_code_lines))

        # 7. Machine Learning Workflow & AutoML
        add_md("## 6. Machine Learning Workflow & AutoML\nTraining, evaluating, optimizing, and predicting outcomes from your dataset features. Below is a need-based ML pipeline template.")
        
        ml_code_lines = []
        ml_code_lines.extend([
            "from sklearn.model_selection import train_test_split",
            "from sklearn.impute import SimpleImputer",
            "from sklearn.preprocessing import StandardScaler, OneHotEncoder",
            "from sklearn.compose import ColumnTransformer",
            "from sklearn.pipeline import Pipeline",
            "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor",
            "from sklearn.metrics import classification_report, accuracy_score, mean_squared_error, r2_score",
            "",
            "# 1. Define target column (Predicting the last column of the dataset by default)",
            "target_col = df.columns[-1]",
            "print('Target column selected:', target_col)",
            "",
            "# 2. Separate features (X) and target (y)",
            "X = df.drop(columns=[target_col]).select_dtypes(include=[np.number, 'object', 'category'])",
            "y = df[target_col]",
            "",
            "num_cols = X.select_dtypes(include=np.number).columns.tolist()",
            "cat_cols = X.select_dtypes(exclude=np.number).columns.tolist()",
            "",
            "# 3. Build ColumnTransformer preprocessing pipeline",
            "transformers = []",
            "if num_cols:",
            "    transformers.append(('num', Pipeline([",
            "        ('imputer', SimpleImputer(strategy='median')),",
            "        ('scaler', StandardScaler())",
            "    ]), num_cols))",
            "if cat_cols:",
            "    transformers.append(('cat', Pipeline([",
            "        ('imputer', SimpleImputer(strategy='most_frequent')),",
            "        ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))",
            "    ]), cat_cols))",
            "",
            "preprocessor = ColumnTransformer(transformers=transformers, remainder='drop')",
            "",
            "# 4. Split data (Stratification for classification)",
            "is_classification = y.nunique() <= 15 or y.dtype == 'object'",
            "stratify = y if is_classification else None",
            "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=stratify)",
            "",
            "# 5. Define and train pipeline estimator",
            "if is_classification:",
            "    model = RandomForestClassifier(random_state=42)",
            "    model_name = 'Random Forest Classifier'",
            "else:",
            "    model = RandomForestRegressor(random_state=42)",
            "    model_name = 'Random Forest Regressor'",
            "",
            "pipeline = Pipeline([",
            "    ('preprocessor', preprocessor),",
            "    ('model', model)",
            "])",
            "",
            "print(f'Training {model_name}...')"
        ])

        # Check if actual ledger actions exist
        train_step = next((a for a in reversed(ml_actions) if a['action'] == 'ml_train_v2'), None)
        if train_step:
            p = train_step['params']
            algo = p.get('algorithm')
            features = p.get('feature_columns', [])
            scaling = p.get('scaling_method', 'auto')
            imputation = p.get('imputation_strategy', 'median')
            encoding = p.get('categorical_encoding', 'onehot')
            stratify = p.get('stratify_split', True)
            test_size = p.get('test_size', 0.2)
            
            ml_code_lines.extend([
                f"\n# --- User Trained Custom Pipeline: {algo} ---",
                f"X_custom = df[{features}]",
                f"y_custom = df[target_col]",
                f"stratify_custom = y_custom if (is_classification and {stratify}) else None",
                f"X_tr, X_te, y_tr, y_te = train_test_split(X_custom, y_custom, test_size={test_size}, random_state=42, stratify=stratify_custom)",
                f"",
                f"custom_num = X_custom.select_dtypes(include=np.number).columns.tolist()",
                f"custom_cat = [c for c in X_custom.columns if c not in custom_num]",
                f"",
                f"custom_transformers = []",
                f"if custom_num:",
                f"    num_steps = [('imputer', SimpleImputer(strategy='{imputation}'))]"
            ])
            
            if scaling == 'auto':
                ml_code_lines.extend([
                    f"    is_tree = '{algo}' in [",
                    f"        'random_forest_classifier', 'random_forest_regressor',",
                    f"        'gradient_boosting_classifier', 'gradient_boosting_regressor',",
                    f"        'xgboost_classifier', 'xgboost_regressor',",
                    f"        'lightgbm_classifier', 'lightgbm_regressor',",
                    f"        'decision_tree'",
                    f"    ]",
                    f"    if not is_tree:",
                    f"        num_steps.append(('scaler', StandardScaler()))"
                ])
            elif scaling == 'standard':
                ml_code_lines.append(f"    num_steps.append(('scaler', StandardScaler()))")
            elif scaling == 'robust':
                ml_code_lines.append(f"    num_steps.append(('scaler', RobustScaler()))")
            elif scaling == 'minmax':
                ml_code_lines.append(f"    num_steps.append(('scaler', MinMaxScaler()))")
                
            ml_code_lines.extend([
                f"    custom_transformers.append(('num', Pipeline(num_steps), custom_num))",
                f"if custom_cat:",
                f"    cat_steps = [('imputer', SimpleImputer(strategy='most_frequent'))]"
            ])
            
            if encoding == 'onehot':
                ml_code_lines.append(f"    cat_steps.append(('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False)))")
            elif encoding == 'ordinal':
                ml_code_lines.append(f"    cat_steps.append(('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)))")
                
            ml_code_lines.extend([
                f"    custom_transformers.append(('cat', Pipeline(cat_steps), custom_cat))",
                f"custom_prep = ColumnTransformer(transformers=custom_transformers, remainder='drop')"
            ])

            # Model setup
            if algo == "linear_regression":
                ml_code_lines.append("from sklearn.linear_model import LinearRegression\ncustom_model = LinearRegression()")
            elif algo == "random_forest_regressor":
                ml_code_lines.append("from sklearn.ensemble import RandomForestRegressor\ncustom_model = RandomForestRegressor(random_state=42)")
            elif algo == "gradient_boosting_regressor":
                ml_code_lines.append("from sklearn.ensemble import GradientBoostingRegressor\ncustom_model = GradientBoostingRegressor(random_state=42)")
            elif algo == "ridge":
                ml_code_lines.append("from sklearn.linear_model import Ridge\ncustom_model = Ridge()")
            elif algo == "lasso":
                ml_code_lines.append("from sklearn.linear_model import Lasso\ncustom_model = Lasso()")
            elif algo == "logistic_regression":
                ml_code_lines.append("from sklearn.linear_model import LogisticRegression\ncustom_model = LogisticRegression(max_iter=1000, random_state=42)")
            elif algo == "random_forest_classifier":
                ml_code_lines.append("from sklearn.ensemble import RandomForestClassifier\ncustom_model = RandomForestClassifier(random_state=42)")
            elif algo == "gradient_boosting_classifier":
                ml_code_lines.append("from sklearn.ensemble import GradientBoostingClassifier\ncustom_model = GradientBoostingClassifier(random_state=42)")
            elif algo == "decision_tree":
                ml_code_lines.append("from sklearn.tree import DecisionTreeClassifier\ncustom_model = DecisionTreeClassifier(random_state=42)")
            elif algo == "xgboost_regressor" or algo == "xgboost_classifier":
                ml_code_lines.append("import xgboost as xgb")
                if algo == "xgboost_regressor":
                    ml_code_lines.append("custom_model = xgb.XGBRegressor(random_state=42)")
                else:
                    ml_code_lines.append("custom_model = xgb.XGBClassifier(random_state=42)")
            elif algo == "lightgbm_regressor" or algo == "lightgbm_classifier":
                ml_code_lines.append("import lightgbm as lgb")
                if algo == "lightgbm_regressor":
                    ml_code_lines.append("custom_model = lgb.LGBMRegressor(random_state=42)")
                else:
                    ml_code_lines.append("custom_model = lgb.LGBMClassifier(random_state=42)")
            else:
                ml_code_lines.append("custom_model = RandomForestClassifier(random_state=42)")

            # Tuning parameters
            tune_step = next((a for a in ml_actions if a['action'] == 'ml_tune'), None)
            if tune_step:
                best_params = tune_step['params']['best_params']
                ml_code_lines.append(f"custom_model.set_params(**{best_params})")

            ml_code_lines.extend([
                f"pipeline = Pipeline([('preprocessor', custom_prep), ('model', custom_model)])"
            ])
        else:
            ml_code_lines.extend([
                "pipeline.fit(X_train, y_train)"
            ])

        ml_code_lines.extend([
            "y_pred = pipeline.predict(X_test)",
            "",
            "# 6. Evaluation metrics",
            "if is_classification:",
            "    print('Accuracy:', accuracy_score(y_test, y_pred))",
            "    print('\\nClassification Report:\\n', classification_report(y_test, y_pred))",
            "else:",
            "    print('Mean Squared Error (MSE):', mean_squared_error(y_test, y_pred))",
            "    print('R2 Score:', r2_score(y_test, y_pred))"
        ])

        # 8. Tuning template (Uncommented block template)
        ml_code_lines.extend([
            "\n# 7. Optional Hyperparameter Tuning (Grid Search Cross Validation)",
            "# from sklearn.model_selection import GridSearchCV",
            "# param_grid = {",
            "#     'model__max_depth': [5, 10, None],",
            "#     'model__min_samples_split': [2, 5]",
            "# }",
            "# grid_search = GridSearchCV(pipeline, param_grid, cv=3, n_jobs=-1)",
            "# grid_search.fit(X_train, y_train)",
            "# print('Best Parameters:', grid_search.best_params_)",
            "# pipeline = grid_search.best_estimator_"
        ])

        # 9. Prediction template (Uncommented block template)
        predict_step = next((a for a in ml_actions if a['action'] == 'ml_predict'), None)
        inputs_val = predict_step['params']['inputs'] if predict_step else "{col: [np.nan] for col in X.columns}"
        ml_code_lines.extend([
            "\n# 8. Prediction Simulator on Custom Inputs",
            f"sample_inputs = {inputs_val}",
            "df_sample = pd.DataFrame([sample_inputs])",
            "pred_outcome = pipeline.predict(df_sample)[0]",
            "print(f'Prediction result: {pred_outcome}')"
        ])

        add_code("\n".join(ml_code_lines))

        # Build Notebook Dictionary
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {"name": "ipython", "version": 3},
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.8.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }

        # Save to file
        reports_dir = settings.REPORTS_DIR
        os.makedirs(reports_dir, exist_ok=True)
        filename = f"infinitics_analysis_{uuid.uuid4().hex[:8]}.ipynb"
        file_path = os.path.join(reports_dir, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(notebook, f, indent=2)

        return file_path
