import os
import json
import uuid
from typing import List, Dict, Any
import numpy as np
import pandas as pd
from app.services.data_service import DataService
from app.config import settings

class JupyterService:
    """
    Compiles an Action Ledger into a Kaggle-style Jupyter Notebook (.ipynb).
    """

    @staticmethod
    def generate_notebook(dataset_id: str) -> str:
        """
        Generates a Jupyter Notebook based on the user's recorded actions
        and basic EDA/ML boilerplate. Returns the path to the .ipynb file.
        """
        dataset_info = DataService.get_dataset_info(dataset_id)
        ledger = DataService.get_action_ledger(dataset_id)
        dataset_name = dataset_info.get("filename", "dataset.csv")

        cells = []
        
        # Helper to add markdown cells
        def add_md(text: str):
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [text]
            })

        # Helper to add code cells
        def add_code(code: str):
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [code]
            })

        # 1. Header
        add_md(f"# 📊 Infinitics AI: Automated Analysis Notebook\n\nThis notebook was automatically generated by Infinitics AI based on the interactive data cleaning and analysis you performed on `{dataset_name}`. It contains all the necessary preprocessing, exploratory data analysis (EDA), and basic model setup steps.")

        # 2. Imports
        add_md("## 1. Environment Setup & Imports\nImporting the necessary standard libraries for data manipulation, visualization, and machine learning.")
        add_code("import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport warnings\n\nwarnings.filterwarnings('ignore')\n%matplotlib inline\n\n# Configure visual styling\nsns.set_theme(style='darkgrid', palette='muted')")

        # 3. Data Loading
        add_md(f"## 2. Data Loading\nLoading `{dataset_name}` into a Pandas DataFrame.")
        add_code(f"file_path = '{dataset_name}' # Update this path to where your dataset is stored locally.\ndf = pd.read_csv(file_path)\n\n# Display basic information\ndf.info()\ndisplay(df.head())")

        # Separate actions into buckets
        cleaning_actions = [a for a in ledger if not a['action'].startswith('viz_') and not a['action'].startswith('ml_') and not a['action'].startswith('fe_')]
        fe_actions = [a for a in ledger if a['action'].startswith('fe_')]
        viz_actions = [a for a in ledger if a['action'].startswith('viz_')]
        ml_actions = [a for a in ledger if a['action'].startswith('ml_')]

        # 4. Data Cleaning (From Ledger)
        add_md("## 3. Data Preprocessing & Cleaning\nReplaying the exact cleaning operations performed in the Infinitics UI.")
        
        cleaning_code_lines = []
        if not cleaning_actions:
            cleaning_code_lines.append("# No specific cleaning operations were performed in the UI.")
        
        for idx, step in enumerate(cleaning_actions):
            action = step["action"]
            p = step["params"]
            cleaning_code_lines.append(f"\n# Step {idx+1}: {action}")
            
            if action == "missing_values":
                strat = p.get("strategy")
                cols = p.get("columns")
                cols_str = f"df.columns" if not cols else str(cols)
                if strat == "drop_rows":
                    cleaning_code_lines.append(f"df = df.dropna(subset={cols_str})")
                elif strat == "drop_cols":
                    cleaning_code_lines.append(f"df = df.drop(columns={cols_str})")
                elif strat == "fill_mean":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    if pd.api.types.is_numeric_dtype(df[col]):\n        df[col] = df[col].fillna(df[col].mean())")
                elif strat == "fill_median":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    if pd.api.types.is_numeric_dtype(df[col]):\n        df[col] = df[col].fillna(df[col].median())")
                elif strat == "fill_mode":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    mode_val = df[col].mode()\n    if not mode_val.empty:\n        df[col] = df[col].fillna(mode_val.iloc[0])")
                elif strat == "fill_constant":
                    cleaning_code_lines.append(f"df[{cols_str}] = df[{cols_str}].fillna({repr(p.get('fill_value'))})")
                else:
                    cleaning_code_lines.append(f"# Applied missing value strategy: {strat} on {cols_str}")

            elif action == "remove_duplicates":
                subset = p.get("subset")
                cleaning_code_lines.append(f"df = df.drop_duplicates(subset={subset})")

            elif action == "drop_columns":
                cleaning_code_lines.append(f"df = df.drop(columns={p.get('columns')})")

            elif action == "rename_columns":
                cleaning_code_lines.append(f"df = df.rename(columns={p.get('rename_map')})")

            elif action == "convert_dtype":
                cleaning_code_lines.append(f"df['{p.get('column')}'] = df['{p.get('column')}'].astype('{p.get('target_dtype')}')")

            elif action == "handle_outliers":
                cleaning_code_lines.append(f"# Handled outliers for {p.get('column')} using {p.get('method')} ({p.get('strategy')})")
                if p.get('strategy') == 'remove':
                    cleaning_code_lines.append(f"# Removing {p.get('column')} outliers...")

            elif action == "normalize":
                cleaning_code_lines.append(f"# Normalized {p.get('columns')} using {p.get('method')} scaler")

            elif action == "encode_column":
                cleaning_code_lines.append(f"# Encoded categorical column {p.get('column')} using {p.get('method')} encoding")

            elif action == "sql_query_select_applied":
                q = p.get("query", "")
                q_safe = q.replace('"""', '\\"\\"\\"')
                cleaning_code_lines.extend([
                    f"# Replay applied SQL SELECT preprocessing query:",
                    f"import sqlite3",
                    f"conn = sqlite3.connect(':memory:')",
                    f"df.to_sql('dataset', conn, index=False)",
                    f"query = \"\"\"{q_safe}\"\"\"",
                    f"df = pd.read_sql_query(query, conn)",
                    f"conn.close()"
                ])

            elif action == "sql_query_modified":
                q = p.get("query", "")
                q_safe = q.replace('"""', '\\"\\"\\"')
                cleaning_code_lines.extend([
                    f"# Replay modifying SQL query:",
                    f"import sqlite3",
                    f"conn = sqlite3.connect(':memory:')",
                    f"df.to_sql('dataset', conn, index=False)",
                    f"query = \"\"\"{q_safe}\"\"\"",
                    f"cursor = conn.cursor()",
                    f"if ';' in query:",
                    f"    cursor.executescript(query)",
                    f"else:",
                    f"    cursor.execute(query)",
                    f"conn.commit()",
                    f"df = pd.read_sql_query('SELECT * FROM dataset', conn)",
                    f"conn.close()"
                ])

            else:
                cleaning_code_lines.append(f"# Operation {action} applied with params {p}")

        add_code("\n".join(cleaning_code_lines))

        # 3.5. Local SQL Sandbox & Optional Templates
        add_md("## 3.5. Local SQLite Query Sandbox\nYou can continue preprocessing or exploring this dataset using full SQL syntax locally. Here is the template to query your DataFrame using SQLite:")
        
        sql_sandbox_setup = (
            "import sqlite3\n\n"
            "# 1. Initialize transient in-memory SQLite database\n"
            "conn = sqlite3.connect(':memory:')\n\n"
            "# 2. Load the current DataFrame state into the 'dataset' table\n"
            "df.to_sql('dataset', conn, index=False, if_exists='replace')\n\n"
            "print('Transient SQLite database ready. You can query table: dataset')"
        )
        add_code(sql_sandbox_setup)
        
        add_md("### Pre-configured SQL Query Templates\nBelow are a few pre-configured SQL templates to query, group, and analyze your dataset columns:")
        
        query_preview = (
            "# Run a SELECT query and load the results back into a DataFrame\n"
            "query_1 = 'SELECT * FROM dataset LIMIT 10;'\n"
            "df_preview = pd.read_sql_query(query_1, conn)\n"
            "display(df_preview)"
        )
        add_code(query_preview)

        cat_cols_list = dataset_info.get("column_types", {}).get("categorical", [])
        if cat_cols_list:
            query_agg = (
                f"# Aggregate occurrences of the categorical field '{cat_cols_list[0]}'\n"
                f"query_2 = '''\n"
                f"SELECT `{cat_cols_list[0]}`, COUNT(*) as count\n"
                f"FROM dataset\n"
                f"GROUP BY `{cat_cols_list[0]}`\n"
                f"ORDER BY count DESC\n"
                f"LIMIT 10;\n"
                f"'''\n"
                f"df_counts = pd.read_sql_query(query_2, conn)\n"
                f"display(df_counts)"
            )
            add_code(query_agg)
            
        num_cols_list = dataset_info.get("column_types", {}).get("numeric", [])
        if num_cols_list:
            query_stats = (
                f"# Calculate summary statistics on '{num_cols_list[0]}'\n"
                f"query_3 = '''\n"
                f"SELECT AVG(`{num_cols_list[0]}`) as avg_val,\n"
                f"       MIN(`{num_cols_list[0]}`) as min_val,\n"
                f"       MAX(`{num_cols_list[0]}`) as max_val\n"
                f"FROM dataset;\n"
                f"'''\n"
                f"df_stats = pd.read_sql_query(query_3, conn)\n"
                f"display(df_stats)"
            )
            add_code(query_stats)

        query_cleaning = (
            "# Example: Update values or perform deletion preprocessing via SQL\n"
            "# cursor = conn.cursor()\n"
            "# cursor.execute('DELETE FROM dataset WHERE age < 18')\n"
            "# conn.commit()\n"
            "# df = pd.read_sql_query('SELECT * FROM dataset', conn)\n"
            "# print('New dataset shape:', df.shape)"
        )
        add_code(query_cleaning)

        # 5. EDA & Feature Engineering
        add_md("## 4. Exploratory Data Analysis (EDA) & Feature Engineering\nVisualizing features and applying user-approved feature engineering steps (like polynomial combinations, date extractions, or ratio metrics).")
        
        eda_code = (
            "# Missing Values Heatmap\n"
            "plt.figure(figsize=(10, 6))\n"
            "sns.heatmap(df.isnull(), yticklabels=False, cbar=False, cmap='viridis')\n"
            "plt.title('Missing Values Distribution')\n"
            "plt.show()\n\n"
            "# Distribution of Numerical Features\n"
            "numerical_cols = df.select_dtypes(include=np.number).columns\n"
            "if len(numerical_cols) > 0:\n"
            "    df[numerical_cols].hist(figsize=(15, 10), bins=20, edgecolor='black')\n"
            "    plt.suptitle('Histograms of Numerical Features')\n"
            "    plt.tight_layout()\n"
            "    plt.show()\n\n"
            "# Correlation Matrix Heatmap\n"
            "if len(numerical_cols) > 1:\n"
            "    plt.figure(figsize=(12, 8))\n"
            "    sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)\n"
            "    plt.title('Correlation Matrix')\n"
            "    plt.show()"
        )
        add_code(eda_code)

        fe_code_lines = []
        if fe_actions:
            fe_code_lines.append("# --- Applied Feature Engineering ---")
            for idx, step in enumerate(fe_actions):
                action = step["action"]
                p = step["params"]
                fe_code_lines.append(f"\n# Step {idx+1}: {action}")
                
                if action == "fe_polynomial":
                    fe_code_lines.extend([
                        f"from sklearn.preprocessing import PolynomialFeatures",
                        f"cols = {p.get('columns')}",
                        f"poly = PolynomialFeatures(degree={p.get('degree', 2)}, interaction_only={p.get('interaction_only', False)}, include_bias=False)",
                        f"X_poly = poly.fit_transform(df[cols].dropna())",
                        f"poly_df = pd.DataFrame(X_poly, columns=poly.get_feature_names_out(cols))",
                        f"new_cols = [n for n in poly_df.columns if n not in df.columns]",
                        f"df = pd.concat([df, poly_df[new_cols]], axis=1)"
                    ])
                elif action == "fe_date":
                    col = p.get('column')
                    fe_code_lines.extend([
                        f"df['{col}'] = pd.to_datetime(df['{col}'], errors='coerce')",
                        f"df['{col}_year'] = df['{col}'].dt.year",
                        f"df['{col}_month'] = df['{col}'].dt.month",
                        f"df['{col}_day'] = df['{col}'].dt.day",
                        f"df['{col}_dayofweek'] = df['{col}'].dt.dayofweek",
                        f"# Fill na values",
                        f"for nc in ['{col}_year', '{col}_month', '{col}_day', '{col}_dayofweek']:",
                        f"    df[nc] = df[nc].fillna(df[nc].median() if not df[nc].empty else 0)"
                    ])
                elif action == "fe_ratio":
                    c1 = p.get('column1')
                    c2 = p.get('column2')
                    new_col = p.get('new_feature')
                    fe_code_lines.extend([
                        f"df['{new_col}'] = df['{c1}'] / df['{c2}'].replace(0, np.nan)",
                        f"df['{new_col}'] = df['{new_col}'].fillna(0)"
                    ])
        else:
            fe_code_lines.append("# No custom feature engineering was applied in the UI.")
            
        add_code("\n".join(fe_code_lines))

        # 6. Custom Visualizations
        if viz_actions:
            add_md("## 5. Custom Visualizations\nReproducing the exact custom charts generated in the Infinitics UI.")
            
            seen_viz = set()
            viz_code_lines = []
            
            for step in reversed(viz_actions):
                action = step["action"]
                p = step["params"]
                
                cols_sig = "-".join([str(v) for k, v in p.items() if 'col' in k or 'column' in k])
                sig = f"{action}_{cols_sig}"
                
                if sig in seen_viz:
                    continue
                seen_viz.add(sig)
                
                viz_code_lines.append(f"\n# {action} on {cols_sig}")
                viz_code_lines.append("plt.figure(figsize=(10, 6))")
                
                if action == "viz_histogram":
                    viz_code_lines.append(f"sns.histplot(data=df, x='{p.get('column')}', bins={p.get('bins', 30)}, kde=True)")
                elif action == "viz_bar":
                    if p.get('y_col'):
                        viz_code_lines.append(f"sns.barplot(data=df, x='{p.get('x_col')}', y='{p.get('y_col')}')")
                    else:
                        viz_code_lines.append(f"df['{p.get('x_col')}'].value_counts().head({p.get('top_n', 20)}).plot(kind='bar')")
                elif action == "viz_scatter":
                    hue_str = f", hue='{p.get('color_col')}'" if p.get('color_col') else ""
                    viz_code_lines.append(f"sns.scatterplot(data=df, x='{p.get('x_col')}', y='{p.get('y_col')}'{hue_str})")
                elif action == "viz_line":
                    viz_code_lines.append(f"sns.lineplot(data=df, x='{p.get('x_col')}', y='{p.get('y_col')}')")
                elif action == "viz_box":
                    if p.get('group_col'):
                        viz_code_lines.append(f"sns.boxplot(data=df, x='{p.get('group_col')}', y='{p.get('column')}')")
                    else:
                        viz_code_lines.append(f"sns.boxplot(data=df, y='{p.get('column')}')")
                elif action == "viz_pie":
                    viz_code_lines.append(f"df['{p.get('column')}'].value_counts().head({p.get('top_n', 10)}).plot.pie(autopct='%1.1f%%')\nplt.ylabel('')")
                elif action == "viz_heatmap":
                    viz_code_lines.append(f"sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')")
                elif action == "viz_violin":
                    if p.get('group_col'):
                        viz_code_lines.append(f"sns.violinplot(data=df, x='{p.get('group_col')}', y='{p.get('column')}')")
                    else:
                        viz_code_lines.append(f"sns.violinplot(data=df, y='{p.get('column')}')")
                else:
                    viz_code_lines.append(f"# (Code for {action} omitted in simplified export)")
                    
                viz_code_lines.append("plt.title(f'Custom Chart: {action}')")
                viz_code_lines.append("plt.tight_layout()\nplt.show()")
                
            viz_code_lines.reverse()
            add_code("\n".join(viz_code_lines))

        # 7. Machine Learning Workflow (Cell 5 -> AutoML + ML Workflow, Cell 6-9 dynamically)
        if ml_actions:
            add_md("## 6. Modeling & Predictions Workflow\nReplaying the machine learning workflow configured in the UI.")
            
            ml_code_lines = []
            
            # Target selection
            target_step = next((a for a in ml_actions if a['action'] == 'ml_target_select'), None)
            target_col = "target"
            problem_type = "classification"
            if target_step:
                target_col = target_step['params']['target_column']
                problem_type = target_step['params']['problem_type']
                ml_code_lines.append(f"# Selected target column: '{target_col}' ({problem_type.upper()})")
                ml_code_lines.append(f"target_col = '{target_col}'")

            # Training / Preprocessing Pipeline
            train_step = next((a for a in reversed(ml_actions) if a['action'] == 'ml_train_v2'), None)
            if train_step:
                p = train_step['params']
                algo = p.get('algorithm')
                features = p.get('feature_columns', [])
                scaling = p.get('scaling_method', 'auto')
                imputation = p.get('imputation_strategy', 'median')
                encoding = p.get('categorical_encoding', 'onehot')
                stratify = p.get('stratify_split', True)
                test_size = p.get('test_size', 0.2)
                
                ml_code_lines.extend([
                    f"\n# --- Preprocessing Pipeline & Data Splits ---",
                    f"from sklearn.model_selection import train_test_split",
                    f"from sklearn.impute import SimpleImputer",
                    f"from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder",
                    f"from sklearn.compose import ColumnTransformer",
                    f"from sklearn.pipeline import Pipeline",
                    f"",
                    f"feature_cols = {features}",
                    f"X = df[feature_cols]",
                    f"y = df[target_col]",
                    f"",
                    f"# Prevent data leakage by performing split before fitting preprocessing",
                    f"stratify = y if ('{problem_type}' == 'classification' and {stratify}) else None",
                    f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size={test_size}, random_state=42, stratify=stratify)",
                    f"",
                    f"num_cols = X.select_dtypes(include=np.number).columns.tolist()",
                    f"cat_cols = [c for c in X.columns if c not in num_cols]",
                    f"",
                    f"transformers = []",
                    f"if num_cols:",
                    f"    num_steps = [('imputer', SimpleImputer(strategy='{imputation}'))]"
                ])
                
                if scaling == 'auto':
                    ml_code_lines.extend([
                        f"    is_tree = '{algo}' in [",
                        f"        'random_forest_classifier', 'random_forest_regressor',",
                        f"        'gradient_boosting_classifier', 'gradient_boosting_regressor',",
                        f"        'xgboost_classifier', 'xgboost_regressor',",
                        f"        'lightgbm_classifier', 'lightgbm_regressor',",
                        f"        'decision_tree'",
                        f"    ]",
                        f"    if not is_tree:",
                        f"        num_steps.append(('scaler', StandardScaler()))"
                    ])
                elif scaling == 'standard':
                    ml_code_lines.append(f"    num_steps.append(('scaler', StandardScaler()))")
                elif scaling == 'robust':
                    ml_code_lines.append(f"    num_steps.append(('scaler', RobustScaler()))")
                elif scaling == 'minmax':
                    ml_code_lines.append(f"    num_steps.append(('scaler', MinMaxScaler()))")
                    
                ml_code_lines.extend([
                    f"    transformers.append(('num', Pipeline(num_steps), num_cols))",
                    f"if cat_cols:",
                    f"    cat_steps = [('imputer', SimpleImputer(strategy='most_frequent'))]"
                ])
                
                if encoding == 'onehot':
                    ml_code_lines.append(f"    cat_steps.append(('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False)))")
                elif encoding == 'ordinal':
                    ml_code_lines.append(f"    cat_steps.append(('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)))")
                    
                ml_code_lines.extend([
                    f"    transformers.append(('cat', Pipeline(cat_steps), cat_cols))",
                    f"preprocessor = ColumnTransformer(transformers=transformers, remainder='drop')"
                ])

                # Model initialization
                ml_code_lines.extend([
                    f"\n# --- Model Setup ---",
                    f"# Algorithm: {algo}"
                ])
                if algo == "linear_regression":
                    ml_code_lines.append("from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()")
                elif algo == "random_forest_regressor":
                    ml_code_lines.append("from sklearn.ensemble import RandomForestRegressor\nmodel = RandomForestRegressor(random_state=42)")
                elif algo == "gradient_boosting_regressor":
                    ml_code_lines.append("from sklearn.ensemble import GradientBoostingRegressor\nmodel = GradientBoostingRegressor(random_state=42)")
                elif algo == "ridge":
                    ml_code_lines.append("from sklearn.linear_model import Ridge\nmodel = Ridge()")
                elif algo == "lasso":
                    ml_code_lines.append("from sklearn.linear_model import Lasso\nmodel = Lasso()")
                elif algo == "logistic_regression":
                    ml_code_lines.append("from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(max_iter=1000, random_state=42)")
                elif algo == "random_forest_classifier":
                    ml_code_lines.append("from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(random_state=42)")
                elif algo == "gradient_boosting_classifier":
                    ml_code_lines.append("from sklearn.ensemble import GradientBoostingClassifier\nmodel = GradientBoostingClassifier(random_state=42)")
                elif algo == "decision_tree":
                    ml_code_lines.append("from sklearn.tree import DecisionTreeClassifier\nmodel = DecisionTreeClassifier(random_state=42)")
                elif algo == "xgboost_regressor" or algo == "xgboost_classifier":
                    ml_code_lines.append("import xgboost as xgb")
                    if algo == "xgboost_regressor":
                        ml_code_lines.append("model = xgb.XGBRegressor(random_state=42)")
                    else:
                        ml_code_lines.append("model = xgb.XGBClassifier(random_state=42)")
                elif algo == "lightgbm_regressor" or algo == "lightgbm_classifier":
                    ml_code_lines.append("import lightgbm as lgb")
                    if algo == "lightgbm_regressor":
                        ml_code_lines.append("model = lgb.LGBMRegressor(random_state=42)")
                    else:
                        ml_code_lines.append("model = lgb.LGBMClassifier(random_state=42)")
                else:
                    ml_code_lines.append(f"model = None # Set up model here")

                # Tuning parameters
                tune_step = next((a for a in ml_actions if a['action'] == 'ml_tune'), None)
                if tune_step:
                    best_params = tune_step['params']['best_params']
                    ml_code_lines.append(f"\n# --- Best Hyperparameters (From Tuning Search) ---")
                    ml_code_lines.append(f"best_params = {best_params}")
                    ml_code_lines.append(f"model.set_params(**best_params)")

                # Fit and Evaluation
                ml_code_lines.extend([
                    f"\n# --- Assemble Pipeline & Fit Model ---",
                    f"pipeline = Pipeline([",
                    f"    ('preprocessor', preprocessor),",
                    f"    ('model', model)",
                    f"])",
                    f"pipeline.fit(X_train, y_train)",
                    f"y_pred = pipeline.predict(X_test)",
                    f"",
                    f"# --- Evaluation Metrics ---"
                ])

                if problem_type == "classification":
                    ml_code_lines.extend([
                        f"from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report",
                        f"print('Accuracy:', accuracy_score(y_test, y_pred))",
                        f"print('Precision (Weighted):', precision_score(y_test, y_pred, average='weighted', zero_division=0))",
                        f"print('Recall (Weighted):', recall_score(y_test, y_pred, average='weighted', zero_division=0))",
                        f"print('F1-Score (Weighted):', f1_score(y_test, y_pred, average='weighted', zero_division=0))",
                        f"print('\\nClassification Report:\\n', classification_report(y_test, y_pred))"
                    ])
                else:
                    ml_code_lines.extend([
                        f"from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score",
                        f"print('MAE:', mean_absolute_error(y_test, y_pred))",
                        f"print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred)))",
                        f"print('R2 Score:', r2_score(y_test, y_pred))"
                    ])

            # Prediction
            predict_step = next((a for a in ml_actions if a['action'] == 'ml_predict'), None)
            if predict_step:
                inputs = predict_step['params']['inputs']
                ml_code_lines.extend([
                    f"\n# --- Pipeline Custom Prediction ---",
                    f"sample_input = {inputs}",
                    f"df_sample = pd.DataFrame([sample_input])",
                    f"sample_pred = pipeline.predict(df_sample)[0]",
                    f"print(f'Prediction for sample: {{sample_pred}}')"
                ])

            add_code("\n".join(ml_code_lines))

        # Build Notebook Dictionary
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {"name": "ipython", "version": 3},
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.8.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }

        # Save to file
        reports_dir = settings.REPORTS_DIR
        os.makedirs(reports_dir, exist_ok=True)
        filename = f"infinitics_analysis_{uuid.uuid4().hex[:8]}.ipynb"
        file_path = os.path.join(reports_dir, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(notebook, f, indent=2)

        return file_path
