/**
 * HomePage — Infinitics AI
 * Comprehensive Data Analytics & Machine Learning Platform
 * Rebuilt using a premium, dark-mode glassmorphic design system generated by Stitch.
 */

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link, useNavigate } from 'react-router-dom';
import {
  Brain, BarChart2, Upload, Zap, Shield, TrendingUp,
  ChevronRight, Star, Database, Sparkles,
  GitMerge, Activity, UserPlus, ArrowRight, Rocket
} from 'lucide-react';
import { useStore } from '../store/useStore';
import InteractiveBackground from '../components/layout/InteractiveBackground';

const fadeUp: any = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } },
};

const stagger: any = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

const FEATURES = [
  { icon: Upload, title: 'Instant Dataset Ingestion', description: 'Drag & drop CSV or Excel files. Automated type inference, shape detection, and real-time schema validation.', color: '#6366f1' },
  { icon: Brain, title: 'Gemini AI Insights', description: 'Executive summaries, actionable business recommendations, and natural language Q&A against your data.', color: '#8b5cf6' },
  { icon: BarChart2, title: '20+ Chart Visualizations', description: 'Interactive histograms, heatmaps, 3D scatter, violin plots, treemaps, and boxplots powered by Plotly.', color: '#a855f7' },
  { icon: Zap, title: 'Automated EDA Engine', description: 'Automated distribution analysis, Pearson & Spearman correlations, missing value maps, and outlier detection.', color: '#ec4899' },
  { icon: TrendingUp, title: 'AutoML & Model Comparison', description: 'Auto-detect regression vs classification. Train 15+ ML models, compare metrics, ROC curves, and feature importance.', color: '#14b8a6' },
  { icon: Shield, title: 'Data Cleaning & Transformation', description: 'One-click imputation, Z-score/IQR outlier handling, one-hot encoding, and feature scaling.', color: '#f59e0b' },
  { icon: GitMerge, title: 'Feature Engineering Studio', description: 'PCA dimensionality reduction, polynomial features, variance thresholding, and mutual information scoring.', color: '#10b981' },
  { icon: Activity, title: 'Statistical Hypothesis Suite', description: 'Student’s T-tests, ANOVA, Chi-square tests of independence, Shapiro-Wilk normality tests, and confidence intervals.', color: '#3b82f6' },
];

const TESTIMONIALS = [
  {
    name: 'Dr. Sarah Chen',
    role: 'Lead Data Scientist @ FinTech Corp',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzGXmuQl-A4F7Jeq_KtOARxDLp4_SpuOT4XlGh7sK6_a3hq4Dlkpnz657mUox3n6ESKN2pDD_Ff_pMT1Pcsu7TLp53nKDFlcvyxheWnRrqAKxL3sCBBJoCX_ej7slJUsLbP4pOqA7gk9xYH4sBP8WDBwEE9kmh9-Y59zSyNdCZImHKXXeeQ_uY3bydrhfjPzI0vgWCEdaYiyp0M-Aklwrl7Wnos5F0UEllD7h6Cu-aNUkOIiV92Um01sy_zZwwDRRR7cdbHcQZWOEw',
    text: 'Infinitics AI replaced my entire manual EDA workflow. What used to take 3 hours now takes under 2 minutes. The auto-generated executive briefings are extraordinarily accurate.',
    rating: 5,
  },
  {
    name: 'Marcus Thorne',
    role: 'ML Engineer @ AI Studio',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCi8ggdl9n12AZSKEnZJX2fhm-l6FS1Dw6jkh1dK3JgvN5D_Dgrw7I3dQdGKavxx6O7C39A4Xdp15ghc2APo0N1IL5LcB33bSrKhLHifVF5_kfXMqJKbTr_rP_81wkQY62xHmvf33aArTP3MfFZ3XqRXWyIq9M6kYhkxLh2t6tvFpZuCNz7NFCqrqgkm4KAYqJJ4o4fDgzu12pRRgMWT55mIJHcpqmacI-fkOwfhiQyBs_SMl-JAYDiUaEsLklPxS2P4x2U4ZiLCjg7',
    text: 'The ML module is brilliant. It detects task types, trains multiple classifiers/regressors simultaneously, and gives me feature importance rankings right in the browser.',
    rating: 5,
  },
];

export default function HomePage() {
  const navigate = useNavigate();
  const [mousePos, setMousePos] = useState({ x: -1000, y: -1000 });
  const { token, user } = useStore();

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      setMousePos({ x: e.clientX, y: e.clientY });
    };
    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  return (
    <div
      style={{
        minHeight: '100vh',
        background: '#090d16',
        color: '#f8fafc',
        fontFamily: "'Inter', sans-serif",
        position: 'relative',
        overflowX: 'hidden',
      }}
    >
      {/* Dynamic Cursor Glowing Orbit Field */}
      <div
        style={{
          position: 'fixed',
          inset: 0,
          background: `radial-gradient(600px circle at ${mousePos.x}px ${mousePos.y}px, rgba(99, 102, 241, 0.08) 0%, rgba(168, 85, 247, 0.03) 45%, transparent 100%)`,
          pointerEvents: 'none',
          zIndex: 0,
        }}
      />

      {/* Interactive Background Canvas */}
      <InteractiveBackground />

      {/* Embedded CSS for custom styles */}
      <style dangerouslySetInnerHTML={{ __html: `
        .glass-card {
          background: rgba(30, 41, 59, 0.4);
          backdrop-filter: blur(20px);
          -webkit-backdrop-filter: blur(20px);
          border: 1px solid rgba(255, 255, 255, 0.08);
          box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
          transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        }
        .glass-card:hover {
          border-color: rgba(99, 102, 241, 0.3);
          box-shadow: 0 12px 40px 0 rgba(99, 102, 241, 0.1);
        }
        .glass-nav {
          background: rgba(9, 13, 22, 0.8);
          backdrop-filter: blur(24px);
          -webkit-backdrop-filter: blur(24px);
          border-bottom: 1px solid rgba(255, 255, 255, 0.08);
        }
        .text-gradient {
          background: linear-gradient(135deg, #818cf8 0%, #a855f7 50%, #ec4899 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }
        .btn-primary {
          background: linear-gradient(135deg, #4f46e5, #7c3aed);
          color: white;
          box-shadow: 0 4px 14px rgba(79, 70, 229, 0.35);
          transition: all 0.3s ease;
        }
        .btn-primary:hover {
          box-shadow: 0 6px 20px rgba(79, 70, 229, 0.5);
          transform: translateY(-2px);
        }
        .btn-secondary {
          background: rgba(129, 140, 248, 0.1);
          border: 1px solid rgba(129, 140, 248, 0.3);
          color: #a5b4fc;
          transition: all 0.3s ease;
        }
        .btn-secondary:hover {
          background: rgba(129, 140, 248, 0.2);
          border-color: #818cf8;
          transform: translateY(-2px);
        }
        .icon-glow-container {
          position: relative;
        }
        .icon-glow-container::before {
          content: '';
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          width: 32px;
          height: 32px;
          background: currentColor;
          filter: blur(14px);
          opacity: 0.25;
          z-index: 0;
        }
      `}} />

      {/* ── Top Navigation Bar ─────────────────────────────────────────────── */}
      <nav className="glass-nav fixed top-0 left-0 w-full z-50 flex justify-between items-center px-6 md:px-12 py-4 border-b border-white/10">
        <div className="flex items-center gap-3">
          <img
            src="/logo.jpg"
            alt="Logo"
            className="w-9 h-9 rounded-lg object-cover"
          />
          <div className="flex items-center gap-2">
            <span className="font-heading font-extrabold text-lg md:text-xl text-white tracking-tight">
              Infinitics AI
            </span>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
              v1.0 Enterprise
            </span>
          </div>
        </div>

        {/* Quick Nav Items */}
        <div className="flex items-center gap-4">
          <Link
            to="/admin/login"
            className="hidden sm:flex items-center gap-2 text-xs font-semibold text-purple-400 bg-purple-500/10 border border-purple-500/20 px-3 py-1.5 rounded-lg hover:bg-purple-500/20 transition-all"
          >
            <Shield size={13} /> Admin Portal
          </Link>

          <Link
            to={token ? '/dashboard/upload' : '/login'}
            className="flex items-center gap-1.5 text-xs font-bold text-slate-300 hover:text-white transition-colors py-1.5 px-3"
          >
            <span>{token ? 'Open Workspace' : 'Sign In'}</span>
            <ArrowRight size={14} />
          </Link>
        </div>
      </nav>

      {/* ── Hero Section ───────────────────────────────────────────────────── */}
      <main className="max-w-7xl mx-auto px-6 md:px-12 pt-[140px] pb-20 flex flex-col gap-20">
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center min-h-[580px]">
          {/* Left Column: Title and details */}
          <div className="lg:col-span-7 flex flex-col gap-6">
            <div className="inline-flex items-center self-start px-4 py-1.5 rounded-full border border-indigo-500/30 bg-indigo-500/10 gap-2">
              <span className="w-2 h-2 rounded-full bg-indigo-400 animate-pulse"></span>
              <span className="text-[10px] font-bold text-indigo-300 uppercase tracking-widest">
                ENTERPRISE AI DATA ANALYTICS & ML
              </span>
            </div>

            <h1 className="font-heading text-4xl md:text-6xl font-extrabold text-white leading-tight tracking-tight">
              Upload Data. <br />
              <span className="text-gradient">Get AI Insights</span> &amp; <br />
              Train ML Models Instantly.
            </h1>

            <p className="text-base md:text-lg text-slate-400 max-w-2xl leading-relaxed">
              The all-in-one platform for rapid data exploration, automated feature engineering, and high-performance model training. Built for enterprise scale.
            </p>

            {/* Feature Pills */}
            <div className="flex flex-wrap gap-3 mt-2">
              {[
                { icon: Zap, label: 'Auto EDA', color: 'text-indigo-400' },
                { icon: BarChart2, label: '20+ Charts', color: 'text-purple-400' },
                { icon: TrendingUp, label: '15+ ML Models', color: 'text-pink-400' },
              ].map(({ icon: Icon, label, color }) => (
                <div
                  key={label}
                  className="flex items-center gap-2 px-3.5 py-1.5 rounded-lg bg-slate-800/40 border border-white/5"
                >
                  <Icon className={color} size={15} />
                  <span className="text-xs font-semibold text-slate-300">{label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Right Column: Interactive Login/Register Card */}
          <div className="lg:col-span-5 relative">
            <div className="absolute inset-0 bg-indigo-500/10 blur-[100px] rounded-full -z-10"></div>
            <div className="glass-card rounded-2xl p-8 relative flex flex-col gap-6">
              <div className="flex flex-col gap-1.5 text-center border-b border-white/5 pb-6">
                {/* Visual Accent Icon */}
                <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-indigo-600 to-purple-600 flex items-center justify-center mx-auto mb-3 shadow-lg shadow-indigo-500/20">
                  <Rocket size={22} className="text-white" />
                </div>
                <h3 className="font-heading text-xl md:text-2xl font-bold text-white">
                  {token && user ? 'Welcome Back!' : 'Get Started Today'}
                </h3>
                <p className="text-xs md:text-sm text-slate-400">
                  {token && user
                    ? 'Your workspace is ready. Continue analyzing and training models.'
                    : 'Access automated EDA, 20+ charts, AI insights & 15+ ML models.'}
                </p>
              </div>

              <div className="flex flex-col gap-4">
                <Link
                  to={token ? '/dashboard/upload' : '/login'}
                  className="btn-primary rounded-xl py-3.5 font-bold text-sm flex justify-center items-center gap-2 w-full text-center"
                >
                  <span>{token ? 'Open Workspace' : 'Sign In to Workspace'}</span>
                  <ChevronRight size={16} />
                </Link>

                {!(token && user) && (
                  <Link
                    to="/register"
                    className="btn-secondary rounded-xl py-3.5 font-bold text-sm flex justify-center items-center gap-2 w-full text-center"
                  >
                    <UserPlus size={16} />
                    <span>Create Free Account</span>
                  </Link>
                )}
              </div>

              {/* Divider */}
              <div className="relative text-center my-1">
                <div className="absolute top-1/2 left-0 right-0 border-t border-white/5" />
                <span className="relative bg-[#0d131f] px-3 text-[10px] text-slate-500 uppercase tracking-widest font-semibold">
                  Quick Launchers
                </span>
              </div>

              {/* Quick Launchers */}
              <div className="grid grid-cols-2 gap-3">
                <Link
                  to="/dashboard/upload"
                  className="flex items-center justify-center gap-2 py-2.5 rounded-lg bg-slate-800/30 border border-white/5 hover:border-indigo-500/30 text-xs font-semibold text-slate-300 hover:text-white transition-all"
                >
                  <Database size={13} className="text-cyan-400" />
                  <span>Analyst</span>
                </Link>
                <Link
                  to="/admin/login"
                  className="flex items-center justify-center gap-2 py-2.5 rounded-lg bg-slate-800/30 border border-white/5 hover:border-purple-500/30 text-xs font-semibold text-slate-300 hover:text-white transition-all"
                >
                  <Shield size={13} className="text-indigo-400" />
                  <span>Admin</span>
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* ── Capabilities Showcase Grid ────────────────────────────────────── */}
        <section className="flex flex-col gap-12 py-10">
          <div className="text-center flex flex-col gap-3">
            <h2 className="font-heading text-3xl md:text-4xl font-extrabold text-white">
              Enterprise Capabilities
            </h2>
            <p className="text-sm md:text-base text-slate-400 max-w-2xl mx-auto leading-relaxed">
              Accelerate your workflow from raw data to deployed models with our integrated suite of tools.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map(({ icon: Icon, title, description, color }) => (
              <div
                key={title}
                className="glass-card rounded-2xl p-6 flex flex-col gap-4 hover:-translate-y-1 transition-transform duration-300"
              >
                <div
                  style={{ color }}
                  className="icon-glow-container w-11 h-11 rounded-xl bg-white/5 flex items-center justify-center z-10"
                >
                  <Icon size={20} className="relative z-10" />
                </div>
                <h4 className="font-heading text-base font-bold text-white">
                  {title}
                </h4>
                <p className="text-xs text-slate-400 leading-relaxed">
                  {description}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* ── Testimonials ─────────────────────────────────────────────────── */}
        <section className="py-10">
          <h2 className="font-heading text-3xl md:text-4xl font-extrabold text-white text-center mb-12">
            Trusted by Industry Leaders
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {TESTIMONIALS.map(({ name, role, avatar, text, rating }) => (
              <div
                key={name}
                className="glass-card rounded-2xl p-6 relative overflow-hidden flex flex-col gap-5 justify-between"
              >
                <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />
                <div className="flex flex-col gap-4 relative z-10">
                  <div className="flex gap-1 text-amber-500">
                    {Array.from({ length: rating }).map((_, i) => (
                      <Star key={i} size={14} fill="currentColor" />
                    ))}
                  </div>
                  <p className="text-sm text-slate-300 italic leading-relaxed">
                    "{text}"
                  </p>
                </div>

                <div className="flex items-center gap-3 relative z-10 mt-2 border-t border-white/5 pt-4">
                  <div className="w-10 h-10 rounded-full overflow-hidden border border-white/10 bg-slate-800">
                    <img className="w-full h-full object-cover" src={avatar} alt={name} />
                  </div>
                  <div>
                    <h5 className="text-xs font-bold text-white">{name}</h5>
                    <span className="text-[10px] text-slate-400">{role}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* ── Footer ────────────────────────────────────────────────────────── */}
      <footer className="w-full py-12 px-6 md:px-12 flex flex-col md:flex-row justify-between items-center gap-6 bg-slate-950/40 border-t border-white/5">
        <span className="font-heading font-bold text-lg text-white">Infinitics AI</span>
        <div className="flex flex-wrap justify-center gap-6">
          <Link to="/login" className="text-xs text-slate-400 hover:text-white transition-colors">User Portal</Link>
          <Link to="/admin/login" className="text-xs text-indigo-400 font-semibold hover:text-indigo-300 transition-colors">Admin Center</Link>
          <Link to="/register" className="text-xs text-slate-400 hover:text-white transition-colors">Register</Link>
        </div>
        <span className="text-xs text-slate-500">
          © {new Date().getFullYear()} Infinitics AI. Enterprise-Grade Intelligence.
        </span>
      </footer>
    </div>
  );
}
